# Generated by Django 5.1.1 on 2024-09-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('location', models.CharField(max_length=150, verbose_name='Location')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price pro night')),
                ('category', models.CharField(choices=[('Hotel', 'Hotel'), ('Room', 'Room'), ('Hostel', 'Hostel'), ('Suite', 'Suite'), ('House', 'House')], max_length=50, null=True)),
                ('rooms_amount', models.PositiveIntegerField(max_length=20, verbose_name='Number of rooms')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Apartment',
                'ordering': ['-created_at'],
            },
        ),
    ]
