# Generated by Django 5.1.1 on 2024-09-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='rooms_amount',
            field=models.PositiveIntegerField(verbose_name='Number of rooms'),
        ),
    ]
