# Generated by Django 5.1.1 on 2024-09-15 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='owner',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='owned_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
