# Generated by Django 5.1.1 on 2024-09-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_reservation_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='owner',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('reserved', 'Reserved')], default='free', max_length=10, verbose_name='Status'),
        ),
    ]
