# Generated by Django 5.1.1 on 2024-09-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_reservation_apartment_is_deleted_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
