# Generated by Django 5.1.1 on 2024-09-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_reservation_owner_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('reserved', 'Reserved')], default='reserved', max_length=10, verbose_name='Status'),
        ),
    ]
