# Generated by Django 5.1.1 on 2024-09-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_apartment_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='rating',
        ),
        migrations.AddField(
            model_name='apartment',
            name='objects_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, verbose_name='Rating'),
        ),
    ]
