# Generated by Django 5.1.1 on 2024-09-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_apartment_rating_apartment_objects_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Deleted At'),
        ),
    ]
