# Generated by Django 5.1.1 on 2024-09-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_reservation_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Deleted'),
        ),
    ]
